feat: add updateIndex API
isomorphic-git/isomorphic-git pull request #1517
Opened 2022-03-16 12:16 UTC by SamVerschueren

closes #1494

I've added a new API, which is the `updateIndex` API. This is based on the [git update-index](https://git-scm.com/docs/git-update-index) command.

The current implementation allows for adding, removing, force-removing files on disk, or files which are virtual and only live in the object database. The latter use case covers `git update-index --cacheinfo <mode>,<object>,<file>`.

I'm throwing errors based on how `git update-index` throws. I was back-and-forth on adding new error types, but wasn't sure so I worked with what was already there.

I've added quite some tests to it, and tested this new API locally already with the tool that I'm building and seems to work like it should.

## I'm adding a new command:

- [x] add as a new file in `src/api` (and `src/commands` if necessary)
- [x] add command to `src/index.js`
- [x] update `__tests__/test-exports.js`
- [x] create a test in `src/__tests__`
- [x] document the command with a JSDoc comment
- [x] add page to the Docs Sidebar `website/sidebars.json`
- [x] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "feat: add updateIndex API"

2022-03-16 14:35 UTC, jcubic requested changes
Please if possible add filepath as string and array of strings. This is a recent change (I think in git.add) and it would be nice to have the same in this API.
**question**: how it will work when the file is in gitigore? Does the update index is affected by gitignore? If so then please add proper code (you can check code for git add) and unit test for gitignore.

2022-03-16 17:49 UTC, SamVerschueren commented
The array filepath list is pretty clear when removing files. But I'm not sure what to do for adding and could use some feedback.

Just adding regular files is pretty clear as well. (ignoring common properties like `fs` for simplicity)

```ts
await git.updateIndex({
    add: true,
    filepath: ['readme.md', 'package.json']
});
```

But when passing in an `oid`, it doesn't really make sense to provide multiple file paths.

```ts
await git.updateIndex({
    add: true,
    filepath: ['readme.md', 'package.json'],
    oid: '...'
});
```

I think we might have 3 options here
1. We throw an error. (Not a big fan of this one)
2. We just allow it, and then the same object from the object database will be added 3 times.
3. We remove `oid` and `mode` from the root object and allow `string|object|(string | object)[]` as `filepath`.

The 3rd option would then look like this

```ts
await git.updateIndex({
    add: true,
    filepath: [
		{
			filepath: 'readme.md',
			oid: '...'
		}
        'package.json'
	]
});
```

If we go with this, I see 2 (small) issues.
1. `filepath` is not really a good property key, I guess it should be renamed to `files` then or something
2. Defining this in JSDoc seems to be impossible. It seems complains about nested properties in this scenario.

```
 * @param {string|string[]|object} args.filepath - File to act upon.
 * @param {string} args.filepath.oid -
```

<img width="792" alt="image" src="https://user-images.githubusercontent.com/1913805/158655007-46f2c9bf-4086-4b52-9762-793812adb506.png">

2022-03-16 20:28 UTC, jcubic commented
If it doesn't make sense to use an array with oid, then just throw an error. But it should be documented that array works only for adding.

2022-03-16 20:32 UTC, jcubic commented
I'm thinking, the reason why filepath was an array was that adding each file was really slow. Maybe if updateIdndex doesn't have such problems, then maybe we should leave it as is. Using single string. Especially if it's tricky. What do you think?

2022-03-17 06:40 UTC, SamVerschueren commented
I'm wondering if `add` was slow because it constantly had to parse the ignore rules for every add you do 🤔 . That is not the case for `updateIndex`. I'm definitely ok with leaving it as is if you are all ok with this.

2022-03-19 14:40 UTC, jcubic approved these changes

2022-03-19 14:41 UTC, jcubic commented
If so I'm merging the PR, thanks.

2022-03-19 14:41 UTC, merged