feat(checkout, clone, push): Add 'onPrePush' and 'onPostCheckout'
isomorphic-git/isomorphic-git pull request #1797
Opened 2023-07-31 17:49 UTC by CoalZombik

## I'm adding a parameter to an existing command X:

- [x] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [x] document the parameter in the JSDoc comment above the function
- [x] add a test case in `__tests__/test-X.js` if possible
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "feat(X): Added 'bar' parameter"
- [x] add page to the Docs Sidebar `website/sidebars.json`

Closes #1186

I added new documentation `website/sidebars.json`, but I don't know how to handle versioned variants of documentation.

2023-08-01 19:10 UTC, jcubic requested changes
Few comments

2023-08-01 19:10 UTC, jcubic commented on docs/onPostCheckout.md
> +  }
Wrong hook in docs

2023-08-01 19:10 UTC, jcubic commented on docs/onPrePush.md
> +This callback is implemented as an equivalent to the canonical git `pre-push` hook. An `onPrePush` function is passed an object containing information about the target remote and `url`, local and rem
I would reverse the values. I know that on Linux exit code 0 is all fine, but in JavaScript true is all fine, and false is that something is wrong. So this is not very intuitive.

2023-08-01 19:10 UTC, jcubic commented on src/commands/push.js
> +    if (hookCancel) throw new UserCanceledError()
Reverse the condition

2023-08-01 19:10 UTC, jcubic requested changes
Few comments

2024-04-02 00:15 UTC, jcubic commented
Sorry for late reply. Did you change something? I didn't get any notification from GitHub. And you didn't reply to my comments.

2024-04-03 19:46 UTC, CoalZombik commented
Yes, I applied changes that you suggested.

Sorry, it probably my fault, I expected that re-requesting a review will send you a notification.

2024-05-28 17:12 UTC, jcubic commented
Hey, sorry for late response, I totally forget about this Review. I've found my old notes where I did add a link to the PR.

Looks good.

2024-05-28 17:12 UTC, merged

2024-05-28 17:13 UTC, jcubic reviewed
Looks good